name: MonteCarloEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.9
  - r-base=4.3.3        
  - rpy2==3.4.5
  - numpy
  - pandas
  - streamlit
  - plotly
  - matplotlib
  - scipy
  - yfinance